### ISSUE TITLE
请教op编译如何切换luci 23.05版本

### ISSUE THREAD

**Issue by ManuZhu0728** [haiibo/packages#1]
大佬好！

打扰了，实在不知道怎么联系到您，所以冒昧在这里开了一个issue

今天下午lean群里说LEDE源码已[支持luci 23.05切换](https://github.com/coolsnowwolf/lede/commit/1531aa758eed60b556d3e0b2731f7b743c43c51a)，所以我想请教一下在大佬你的[自动编译仓库](https://github.com/haiibo/OpenWrt)里如何进行这个版本切换

谢谢大佬！

**Comment by haiibo** [comment]
lede 默认使用的是23.05
![Snipaste_2024-11-11_00-30-31](https://github.com/user-attachments/assets/cedb35b5-12c5-4cfc-b1d0-67428bc53ff8)
如需切换在对应前面添加#注释即可
